django/Feeder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # localhost:8036/
    url(r'^', include(('home.urls', 'home'))),
    # localhost:8036/admin/
    url(r'^admin/', admin.site.urls),
    # localhost:8036/special_admin/
    url(r'^special_admin/', include(('special_admin.urls', 'special_admin'))),
    # localhost:8036/android/
    url(r'^android/', include(('android.urls', 'android'))),
    # localhost:8036/instructor_login/
    url(r'^instructor_login/', include(('instructor_login.urls', 'instructor_login'))),
    #
    url('', include(('social.apps.django_app.urls', 'social'), namespace='social')),
    url('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
]

django/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # localhost:8036/
    url(r'^$', views.home, name='home'),
]

django/instructor_login/urls.py
from django.conf.urls import url
from . import views

app_name = 'instructor_login'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^auth/$', views.auth_view, name='auth_view'),
    # you need to modify this#add variable#restrict regex
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^invalid/$', views.invalid, name='invalid'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    url(r'^register_failure/$', views.register_failure, name='register_failure'),
    url(r'^course/(?P<pk>[1-9][0-9]*)/tasks/$', views.tasks, name='tasks'),
    # localhost:8036/special_admin/course/<pk>/task/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/task/new/$', views.new_task, name='new_task'),
    # localhost:8036/special_admin/task/<task_pk>/
    url(r'^task/(?P<pk>[1-9][0-9]*)/$', views.old_task, name='old_task'),
    url(r'^task_redirect/$', views.tasks_redirect, name='tasks_redirect'),
    url(r'^courses/$', views.courses, name='courses'),

    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/forms/$', views.feedback_forms, name='feedback_forms'),
    # localhost:8036/special_admin/course/<pk>/feedback/form/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/form/new/$', views.new_feedback_form, name='new_feedback_form'),
    # localhost:8036/special_admin/feedback/form/<task_pk>/
    url(r'^feedback/form/(?P<pk>[1-9][0-9]*)/$', views.old_feedback_form, name='old_feedback_form'),

]

django/instructor_login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class MyForm(UserCreationForm):
    email = forms.EmailField(required=True, max_length=60)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = (self.cleaned_data['email'])
        if commit:
            user.save()

        return user

django/instructor_login/views.py
from datetime import datetime

from django.contrib import auth
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponsePermanentRedirect as PerRedirect
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from special_admin import datetime_helper
from special_admin.models import Course, Task, FeedBackForm, FeedbackResponse, Student
from special_admin.static_strings import FeedbackStrings as fbs
from .forms import MyForm

# need to check whether to add extra project


dict = {}


# Create your views here.
def login(request):
    # template = loader.get_template('instructor_login/login.html')
    user = request.user
    if request.user.is_active:
        return render(request, 'instructor_login/loggedin.html', {'user': request.user})
    return render(request, 'instructor_login/login.html', {'user': request.user})


def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        url = '/instructor_login/loggedin/'
        return HttpResponseRedirect(url)
    else:
        url = '/instructor_login/invalid/'
        return HttpResponseRedirect(url)


def loggedin(request):
    # template = loader.get_template('instructor_login/loggedin.html')
    context = {'full_name': request.user.username}
    return render(request, 'instructor_login/loggedin.html', {'user': request.user})


def invalid(request):
    # template = loader.get_template('instructor_login/loggedin.html')
    # context = {'full_name' : request.user.username}
    return render(request, 'instructor_login/invalid.html')


def logout(request):
    # template = loader.get_template('instructor_login/loggedin.html')
    auth.logout(request)
    return render(request, 'instructor_login/logout.html')


def register(request):
    # template = loader.get_template('instructor_login/loggedin.html')

    if request.method == 'POST':
        form = MyForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)

            form.save()
            return render(request, 'instructor_login/register_success.html', {'form': form})
        else:
            return render(request, 'instructor_login/register_failure.html', {'form': form})

    args = {}
    args['form'] = MyForm()
    return render(request, 'instructor_login/register.html', args)


def register_success(request):
    # template = loader.get_template('instructor_login/loggedin.html')

    return render(request, 'instructor_login/register_success.html')


def register_failure(request):
    # template = loader.get_template('instructor_login/loggedin.html')

    return render(request, 'instructor_login/register_failure.html', dict)


def tasks(request, pk):
    all_courses = Course.objects.all()
    selected_course = get_object_or_404(Course, pk=pk)
    selected_course_tasks = selected_course.task_set.all()
    finished_tasks = []
    remaining_tasks = []
    present_datetime = datetime.now()
    for task_iter in selected_course_tasks:
        task_deadline = datetime_helper.get_datetime(task_iter.deadline)
        if task_deadline <= present_datetime:
            finished_tasks.append(task_iter)
        else:
            remaining_tasks.append(task_iter)

    if request.method == 'POST':
        if 'delete' in request.POST:
            delete_task = get_object_or_404(Task, pk=request.POST['delete'])
            delete_task.delete()
            selected_course_tasks = selected_course.task_set.all()
            finished_tasks = []
            remaining_tasks = []
            present_datetime = datetime.now()
            for task_iter in selected_course_tasks:
                task_deadline = datetime_helper.get_datetime(task_iter.deadline)
                if task_deadline <= present_datetime:
                    finished_tasks.append(task_iter)
                else:
                    remaining_tasks.append(task_iter)

            return render(request, 'instructor_login/task_crud/tasks.html', {'course': selected_course,
                                                                             'all_course': all_courses,
                                                                             'user': request.user,
                                                                             'finished_tasks': finished_tasks,
                                                                             'remaining_tasks': remaining_tasks,
                                                                             'total': len(finished_tasks) + len(
                                                                                 remaining_tasks)})

    elif request.method == 'GET':
        # special admin logged in
        # if request.session.get(sk.instructor_login_logged, False):
        return render(request, 'instructor_login/task_crud/tasks.html', {'course': selected_course,
                                                                         'all_course': all_courses,
                                                                         'user': request.user,
                                                                         'finished_tasks': finished_tasks,
                                                                         'remaining_tasks': remaining_tasks,
                                                                         'total': len(finished_tasks) + len(
                                                                             remaining_tasks)})
        # NOT logged in
        # else:
        #     return render(request, 'instructor_login/login.html')


def new_task(request, pk):
    course = get_object_or_404(Course, pk=pk)

    if request.method == 'POST':
        if 'task_tag' in request.POST:
            try:
                Task.objects.get(tag=request.POST['task_tag'])
                return render(request, 'instructor_login/task_crud/new_task.html', {'course': course,
                                                                                    'user': request.user,
                                                                                    'message': 'Task with same Tag already exists'})
            # adding new task
            except ObjectDoesNotExist:
                # changing formats
                date_deadline_str = request.POST['task_deadline_date']
                date_deadline_parts = date_deadline_str.split("-")
                date_deadline = date_deadline_parts[2] + "/" + date_deadline_parts[1] + "/" + date_deadline_parts[0]
                # now date is of format dd/mm/yyyy
                time_deadline_str = request.POST['task_deadline_time']
                time_deadline = time_deadline_str + ":00"
                # now time is of format hh:mm:ss
                date_time_deadline = date_deadline + " " + time_deadline

                _new_task = Task(tag=request.POST['task_tag'], detail=request.POST['task_detail'],
                                 deadline=date_time_deadline)
                # saving task
                _new_task.save()

                # adding to task set of course
                course.task_set.add(_new_task)

                return PerRedirect(reverse('instructor_login:tasks', kwargs={'pk': course.pk}))

    elif request.method == 'GET':
        # special admin logged in
        # if request.session.get(sk.instructor_login_logged, False):
        return render(request, 'instructor_login/task_crud/new_task.html', {'course': course, 'user': request.user,})
        # NOT logged in
        # else:
        #     return render(request, 'instructor_login/login.html')


def old_task(request, pk):
    selected_task = get_object_or_404(Task, pk=pk)
    selected_course = Course.objects.get(pk=selected_task.course_id)
    date_time_parts = selected_task.deadline.split(" ")
    date = date_time_parts[0].split("/")
    time = date_time_parts[1].split(":")

    if request.method == 'POST':
        # delete student
        if 'delete_task' in request.POST:
            selected_task.delete()
            return PerRedirect(reverse('instructor_login:tasks', kwargs={'pk': selected_course.pk}))

        if 'task_tag' in request.POST:
            try:
                Task.objects.get(tag=request.POST['task_tag'])

                # the same tag exists for some other event
                if request.POST['task_tag'] != selected_task.tag:
                    # special admin logged in
                    # if request.session.get(sk.instructor_login_logged, False):
                    return render(request, 'instructor_login/task_crud/old_task.html', {'task': selected_task,
                                                                                        'user': request.user,
                                                                                        'year': date[2],
                                                                                        'month': date[1],
                                                                                        'day': date[0],
                                                                                        'hour': time[0],
                                                                                        'minute': time[1],
                                                                                        'course': selected_course,
                                                                                        'message': 'Task with same Tag already exists'})
                # exists for the same event
                else:

                    # updating old task

django/instructor_login/templates/instructor_login/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

    <meta charset="UTF-8">
    <title>Instructor</title>
    <link rel="icon" href="{% static "instructor_login/logo.png" %}"/>
    <style>
        body {
            font-family: 'VT323', monospace;
            font-size: 20px;
            background-size: cover;
            background-image: url("http://wallpapercave.com/wp/4SSFz3R.png");
        }

        .navbar {
            background-color: rgba(4, 0, 0, 0.85);
        }

        .navbar a {
            color: #ffffff;
        }

        .navbar a:hover {
            color: darkgreen;
        }
    </style>
    {% block specific_css %}{% endblock %}
</head>
<body>

{# navbar #}
{% block navbar %}
    <nav class="navbar" style="border:0;border-radius:0;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home:home' %}"><big>Feed'er</big></a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'instructor_login:courses' %}">Courses</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <a href="{% url 'auth:logout' %}?next={% url 'instructor_login:login' %}">
                    <button class="btn-danger" style="width: 100px;height: 50px;font-size: xx-large">
                        Out
                    </button>
                </a>
            </ul>
        </div>
    </nav>
{% endblock %}

<div id="message" style="display:none;position: fixed;top: 700px;left: 50px;font-size: 50px">
    <script>
        function message_popup(message) {
            $('#message').text('{{ message }}').fadeIn(0).delay(3000).fadeOut(0);
        }

        $(document).ready(function () {
            message_popup();
        });
    </script>
</div>

{% block message %}

{% endblock %}

{# body block #}
{% block body %}

{% endblock %}

</body>
</html>

django/instructor_login/templates/instructor_login/invalid.html
{% extends 'instructor_login/base.html' %}
    {% block navbar %}
    {% endblock %}
{% block body %}
<h2>Invalid details</h2>

<h3>Click <a href = "{% url 'instructor_login:login' %}">here</a> to re-login</h3>
{% endblock %}

django/instructor_login/templates/instructor_login/loggedin.html
{% extends 'instructor_login/base.html' %}
{% block body %}
    <div class="container-fluid">
        {% if user and not user.is_anonymous %}
            <div class="row">
                <div class="col-xs-4"></div>
                <div class="col-xs-4" style="text-align: center;font-size: 90px;">
                    <span id="greeting">Hello {{ user.get_full_name|default:user.username }}!</span>
                </div>
                <div class="col-xs-4"></div>
            </div>
        {% else %}
            <h2>Invalid Access!!!</h2>
            <h2>You need to login as a user before accessing this page</h2>
            <h2><a href="{% url 'instructor_login:login' %}">Click Here to login</a></h2>
        {% endif %}
    </div>
{% endblock %}

django/instructor_login/templates/instructor_login/login.html
    {% extends 'instructor_login/base.html' %}
    {% block navbar %}
    {% endblock %}
    {% block body %}
    {% if user and not user.is_anonymous %}
    {% csrf_token %}
    <a>You are already logged in as {{ user.get_full_name|default:user.username }}!</a>
    <h3><a href="{% url 'auth:logout' %}?next={% url 'instructor_login:login' %}">Click here to logout</a></h3>
    <h3><a href="{% url 'instructor_login:loggedin' %}">Click here to contiunue as same user</a></h3>

   {% else %}

    <div class="container">
        <div class="row" style="text-align: center;font-size: 50px;font-weight: 900">Instructor Login</div>
        <div class="row" style="height: 100px"></div>
        <form action="{% url 'instructor_login:auth_view' %}" method="post" id="form">
            {% csrf_token %}
        <div class="row" style=" font-size: 30px;" >
             <div class="col-xs-2"></div>
            <div class="col-xs-3">
                <label style="font-size: 40px;">UserName</label>
            </div>
            <div class="col-xs-4"  >
                <input type="text" name="username" id="username" placeholder="username" value="">
            </div>
            <div class="col-xs-3 fbk" ><label id="usernameFeedback"></label></div>

        </div>
            <div class="row" style="height: 10px"></div>
        <br>
        <div class="row" style=" font-size: 30px;">
            <div class="col-xs-2"></div>
            <div class="col-xs-3">
                <label style="font-size: 40px;">Password</label>
            </div>
            <div class="col-xs-2">
                <input type="password" name="password" id="password" placeholder="password" value="">
            </div>

            <div class="col-xs-3 fbk"><label id="passwordFeedback"></label></div>

        </div>
        <br>

        <div class="row" style="font-size: 30px;">
            <div class="col-xs-4"></div>
            <div class="col-xs-4" style="text-align:center;">
                <input class="btn-success" type="submit" value="Login" >
            </div>
            <div class="col-xs-4"></div>

        </div>
        </form>

        <div class="row" style="height: 30px"></div>
       <div class="row">
           <div class="col-xs-1"></div>
        <div class="col-xs-4" style="float:left;font-size: 30px;"><a href="{% url 'social:begin' 'facebook' %}?next={% url 'instructor_login:loggedin' %}"><button class="btn-primary" style="font-size:30px">SignIn with Facebook  <i class="fa fa-facebook-square"></i></button></a></div>
         <div class="col-xs-2"></div>
           <div class="col-xs-4"  style="float:right;font-size: 30px;"> <a href="{% url 'social:begin' 'google-oauth2' %}?next={% url 'instructor_login:loggedin' %}"><button class="btn-danger" style="font-size:30px">SignIn with Google  <i class="fa fa-google"></i></button></a></div>
       <div class="col-xs-1"></div>
       </div>
        <div class="row" style="height: 30px"></div>
         <div class="row" style="text-align: center;font-size: 40px;">Not Yet Signed?? Click <a href = "{% url 'instructor_login:register' %}" >here</a>
             to register</div>
        <div class="row" style="height: 30px"></div>
        <div class="row" style="text-align: center;font-size: 40px;"><a href="{% url 'home:home' %}">Homepage</a></div>


    </div>
    {% endif %}
    {% endblock %}

django/instructor_login/templates/instructor_login/logout.html
<h2>Successfully Logged out</h2>
<h3>Click <a href = "{% url 'instructor_login:login' %}">here</a> to re-login</h3>

django/instructor_login/templates/instructor_login/register.html
    {% extends 'instructor_login/base.html' %}
    {% block navbar %}
    {% endblock %}
    {% block body %}
    <div class="container">
        <div class="row" style="text-align: center;font-size: 60px;font-weight: 900">Register Here</div>
        <div class="row" style="height: 100px";></div>
        <form action="{% url 'instructor_login:register' %}" method="post" id="form">
            {% csrf_token %}
        <div class="row" style=" font-size: 30px ;">
             <div class="col-xs-3"></div>
            <div class="col-xs-2">
                <label>User Name</label>
            </div>
            <div class="col-xs-4" style=" font-size: 30px ;">
                <input type="text" name="username" id=id_username placeholder="username" value="">
            </div>
            <div class="col-xs-3 fbk" ><label id="usernameFeedback"></label></div>

        </div><br>
            <div class="row" style="height: 10px";></div>
        <div class="row" style=" font-size: 30px ;">
             <div class="col-xs-3"></div>
            <div class="col-xs-2">
                <label>E-Mail</label>
            </div>
            <div class="col-xs-4">
                <input type="email" name="email" id=id_email placeholder="email" value="">
            </div>
            <div class="col-xs-3 fbk" ><label id="emailFeedback"></label></div>

        </div>
        <br>
            <div class="row" style="height: 10px";></div>
        <div class="row" style=" font-size: 30px ;">
            <div class="col-xs-3"></div>
            <div class="col-xs-2">
                <label>Password</label>
            </div>
            <div class="col-xs-2">
                <input type="password" name="password1" id=id_password1 placeholder="password" value="">
            </div>

            <div class="col-xs-3 fbk"><label id="passwordFeedback"></label></div>

        </div>
        <br>
            <div class="row" style="height: 10px";></div>
        <div class="row" style=" font-size: 30px ;">
            <div class="col-xs-3"></div>
            <div class="col-xs-2">
                <label>Conform Password</label>
            </div>
            <div class="col-xs-2">
                <input type="password" name="password2" id=id_password2 placeholder="re-enter password" value="">
            </div>

            <div class="col-xs-3 fbk"><label id="password2Feedback"></label></div>

        </div>
        <br>
        <div class="row" style="height: 20px";></div>
        <div class="row">
            <div class="col-xs-5"></div>
            <div class="col-xs-3">
                <input class="btn btn-primary btn-lg"   type="submit" value="Register" >
            </div>
            <div class="col-xs-4"></div>

        </div>





        </form>

        <div class="row" style="height: 60px";></div>




    </div>

  {% endblock %}

django/instructor_login/templates/instructor_login/register_failure.html
    {% extends 'instructor_login/base.html' %}
    {% block navbar %}
    {% endblock %}
    {% block body %}
<h1>Registration Failed</h1>
{% if form.errors %}
	<!-- Error messaging -->
	<div id="errors" style="font-size:30px">
		<div class="inner" >
			<p>There were some errors in the information you entered. Please correct the following:</p>
			{{ form.non_field_errors }}
			<ul>
				{% for field in form %}
					{% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
				{% endfor %}
			</ul>
		</div>
        <a href = "{% url 'instructor_login:register' %}">Click here to register again</a>
	</div>
	<!-- /Error messaging -->
{% endif %}
	{% endblock %}

django/instructor_login/templates/instructor_login/register_success.html
    {% extends 'instructor_login/base.html' %}
    {% block navbar %}
    {% endblock %}
    {% block body %}

<h2>Successfully Registered</h2>
<h3>Click <a href = "{% url 'instructor_login:login' %}">here</a> to re-login</h3>


{% endblock %}