django/Feeder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # localhost:8036/
    url(r'^', include(('home.urls', 'home'))),
    # localhost:8036/admin/
    url(r'^admin/', admin.site.urls),
    # localhost:8036/special_admin/
    url(r'^special_admin/', include(('special_admin.urls', 'special_admin'))),
    # localhost:8036/android/
    url(r'^android/', include(('android.urls', 'android'))),
    # localhost:8036/instructor_login/
    url(r'^instructor_login/', include(('instructor_login.urls', 'instructor_login'))),
    #
    url('', include(('social.apps.django_app.urls', 'social'), namespace='social')),
    url('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
]

django/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # localhost:8036/
    url(r'^$', views.home, name='home'),
]

django/instructor_login/urls.py
from django.conf.urls import url
from . import views

app_name = 'instructor_login'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^auth/$', views.auth_view, name='auth_view'),
    # you need to modify this#add variable#restrict regex
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^invalid/$', views.invalid, name='invalid'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    url(r'^register_failure/$', views.register_failure, name='register_failure'),
    url(r'^course/(?P<pk>[1-9][0-9]*)/tasks/$', views.tasks, name='tasks'),
    # localhost:8036/special_admin/course/<pk>/task/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/task/new/$', views.new_task, name='new_task'),
    # localhost:8036/special_admin/task/<task_pk>/
    url(r'^task/(?P<pk>[1-9][0-9]*)/$', views.old_task, name='old_task'),
    url(r'^task_redirect/$', views.tasks_redirect, name='tasks_redirect'),
    url(r'^courses/$', views.courses, name='courses'),

    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/forms/$', views.feedback_forms, name='feedback_forms'),
    # localhost:8036/special_admin/course/<pk>/feedback/form/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/form/new/$', views.new_feedback_form, name='new_feedback_form'),
    # localhost:8036/special_admin/feedback/form/<task_pk>/
    url(r'^feedback/form/(?P<pk>[1-9][0-9]*)/$', views.old_feedback_form, name='old_feedback_form'),

]

django/special_admin/urls.py
from django.conf.urls import url
from . import views

app_name = 'special_admin'

urlpatterns = [
    # localhost:8036/special_admin/home/
    url(r'^home/$', views.home, name='home'),
    # localhost:8036/special_admin/home/restart/
    url(r'^home/restart/$', views.restart, name='restart'),
    # localhost:8036/special_admin/home/tasks_redirect/
    url(r'^home/t_redirect/$', views.tasks_redirect, name='tasks_redirect'),
    # localhost:8036/special_admin/home/fb_forms_redirect/
    url(r'^home/f_redirect/$', views.fb_forms_redirect, name='fb_forms_redirect'),

    # localhost:8036/special_admin/students/
    url(r'^students/$', views.students, name='students'),
    # localhost:8036/special_admin/student/<pk>/
    url(r'^student/(?P<pk>[1-9][0-9]*)/$', views.old_student, name='old_student'),
    # localhost:8036/special_admin/student/new/
    url(r'^students/new/$', views.new_student, name='new_student'),

    # localhost:8036/special_admin/courses/
    url(r'^courses/$', views.courses, name='courses'),
    # localhost:8036/special_admin/course/<pk>/
    url(r'^course/(?P<pk>[1-9][0-9]*)/$', views.old_course, name='old_course'),
    # localhost:8036/special_admin/course/new/
    url(r'^course/new/$', views.new_course, name='new_course'),

    # localhost:8036/special_admin/course/<pk>/tasks/
    url(r'^course/(?P<pk>[1-9][0-9]*)/tasks/$', views.tasks, name='tasks'),
    # localhost:8036/special_admin/course/<pk>/task/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/task/new/$', views.new_task, name='new_task'),
    # localhost:8036/special_admin/task/<task_pk>/
    url(r'^task/(?P<pk>[1-9][0-9]*)/$', views.old_task, name='old_task'),

    # localhost:8036/special_admin/course/<pk>/feedback/forms/
    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/forms/$', views.feedback_forms, name='feedback_forms'),
    # localhost:8036/special_admin/course/<pk>/feedback/form/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/form/new/$', views.new_feedback_form, name='new_feedback_form'),
    # localhost:8036/special_admin/feedback/form/<task_pk>/
    url(r'^feedback/form/(?P<pk>[1-9][0-9]*)/$', views.old_feedback_form, name='old_feedback_form'),

]

django/home/views.py
from django.http import HttpResponsePermanentRedirect as PerRedirect
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse


def home(request):
    return render(request, 'home/home.html')

django/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    <title>Special Admin</title>
    <link rel="icon" href="{% static "special_admin/logo.png" %}" />
    <style>
        body {
            font-family: 'VT323', monospace;
            font-size: 20px;
            background-size: cover;
            background-image: url("http://wallpapercave.com/wp/4SSFz3R.png");
        }

        .navbar {
            background-color: rgba(4, 0, 0, 0.85);
        }

        .navbar a {
            color: #ffffff;
        }

        .navbar a:hover {
            color: darkgreen;
        }
    </style>
    {% block specific_css %}{% endblock %}
</head>
<body>

{# navbar #}
{% block navbar %}
    <nav class="navbar" style="border:0;border-radius:0;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home:home' %}"><big>Feed'er</big></a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'instructor_login:login' %}">Instructor</a></li>
                <li><a href="{% url 'special_admin:home' %}">Special Admin</a></li>
{#                <li><a href="{% url 'special_admin:tasks_redirect' %}">Tasks</a></li>#}
{#                <li><a href="{% url 'special_admin:fb_forms_redirect' %}">Feedback</a></li>#}
            </ul>
        </div>
    </nav>
{% endblock %}

<div id="message" style="display:none;position: fixed;top: 700px;left: 50px;font-size: 50px">
    <script>
        function message_popup(message) {
            $('#message').text('{{ message }}').fadeIn(0).delay(3000).fadeOut(0);
        }

        $(document).ready(function () {
            message_popup();
        });
    </script>
</div>

{% block message %}

{% endblock %}

{# body block #}
{% block body %}

{% endblock %}

</body>
</html>

django/home/templates/home/home.html
{% extends 'home/base.html' %}
{% block body %}
    <div id="greeting1" style="text-align: center;font-size: 500%;display: none">
        Hello
    </div>
    <div id="greeting2" class="container-fluid" style="text-align: center;font-size: 500%;display: none">
        This is Feed'er 36
    </div>
    <script>
        $(document).ready(function () {
            $('#greeting1').slideDown(1000).delay(1000, function () {
                $('#greeting2').slideDown(1000);
            });
        });
    </script>
{% endblock %}