django/Feeder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # localhost:8036/
    url(r'^', include(('home.urls', 'home'))),
    # localhost:8036/admin/
    url(r'^admin/', admin.site.urls),
    # localhost:8036/special_admin/
    url(r'^special_admin/', include(('special_admin.urls', 'special_admin'))),
    # localhost:8036/android/
    url(r'^android/', include(('android.urls', 'android'))),
    # localhost:8036/instructor_login/
    url(r'^instructor_login/', include(('instructor_login.urls', 'instructor_login'))),
    #
    url('', include(('social.apps.django_app.urls', 'social'), namespace='social')),
    url('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
]

django/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # localhost:8036/
    url(r'^$', views.home, name='home'),
]

django/special_admin/urls.py
from django.conf.urls import url
from . import views

app_name = 'special_admin'

urlpatterns = [
    # localhost:8036/special_admin/home/
    url(r'^home/$', views.home, name='home'),
    # localhost:8036/special_admin/home/restart/
    url(r'^home/restart/$', views.restart, name='restart'),
    # localhost:8036/special_admin/home/tasks_redirect/
    url(r'^home/t_redirect/$', views.tasks_redirect, name='tasks_redirect'),
    # localhost:8036/special_admin/home/fb_forms_redirect/
    url(r'^home/f_redirect/$', views.fb_forms_redirect, name='fb_forms_redirect'),

    # localhost:8036/special_admin/students/
    url(r'^students/$', views.students, name='students'),
    # localhost:8036/special_admin/student/<pk>/
    url(r'^student/(?P<pk>[1-9][0-9]*)/$', views.old_student, name='old_student'),
    # localhost:8036/special_admin/student/new/
    url(r'^students/new/$', views.new_student, name='new_student'),

    # localhost:8036/special_admin/courses/
    url(r'^courses/$', views.courses, name='courses'),
    # localhost:8036/special_admin/course/<pk>/
    url(r'^course/(?P<pk>[1-9][0-9]*)/$', views.old_course, name='old_course'),
    # localhost:8036/special_admin/course/new/
    url(r'^course/new/$', views.new_course, name='new_course'),

    # localhost:8036/special_admin/course/<pk>/tasks/
    url(r'^course/(?P<pk>[1-9][0-9]*)/tasks/$', views.tasks, name='tasks'),
    # localhost:8036/special_admin/course/<pk>/task/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/task/new/$', views.new_task, name='new_task'),
    # localhost:8036/special_admin/task/<task_pk>/
    url(r'^task/(?P<pk>[1-9][0-9]*)/$', views.old_task, name='old_task'),

    # localhost:8036/special_admin/course/<pk>/feedback/forms/
    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/forms/$', views.feedback_forms, name='feedback_forms'),
    # localhost:8036/special_admin/course/<pk>/feedback/form/new/
    url(r'^course/(?P<pk>[1-9][0-9]*)/feedback/form/new/$', views.new_feedback_form, name='new_feedback_form'),
    # localhost:8036/special_admin/feedback/form/<task_pk>/
    url(r'^feedback/form/(?P<pk>[1-9][0-9]*)/$', views.old_feedback_form, name='old_feedback_form'),

]

django/special_admin/models.py
from __future__ import unicode_literals

from django.db import models


class SpecialAdmin:
    email = "admin@a.b"
    password = "admin"


class Student(models.Model):
    name = models.CharField(max_length=50)
    user_name = models.EmailField(max_length=30)
    password = models.CharField(max_length=20)
    courses = models.ManyToManyField('Course')

    def __str__(self):
        return self.name


class Course(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    students = models.ManyToManyField(Student)

    def __str__(self):
        return self.code + " - " + self.name


class Task(models.Model):
    tag = models.CharField(max_length=50)
    detail = models.CharField(max_length=400)
    deadline = models.CharField(max_length=20)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.tag + "-" + self.deadline + " of " + self.course


class FeedBackForm(models.Model):
    name = models.CharField(max_length=50)
    question_set = models.TextField()
    deadline = models.CharField(max_length=20)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name + "-" + self.deadline + " of " + self.course.name


class FeedbackResponse(models.Model):
    answer_set = models.TextField()
    comment = models.TextField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    feedback_form = models.ForeignKey(FeedBackForm, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.student.user_name + " response to " + str(self.feedback_form.pk)

django/special_admin/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponsePermanentRedirect as PerRedirect, HttpResponse
from datetime import datetime, timedelta
import csv

from Feeder.settings import STUDENT_CSV
from .models import Student, Course, Task, FeedBackForm, SpecialAdmin
from .static_strings import SessionKeys as sk, FeedbackStrings as fbs
from . import datetime_helper


def home(request):
    # POST request
    if request.method == 'POST':

        # Login request
        if 'special_admin_email' in request.POST and 'special_admin_password' in request.POST:
            # Validating SuperUser credentials from the fields statically typed in code
            error_set = {}
            if request.POST['special_admin_email'] != SpecialAdmin.email:
                error_set['email_incorrect'] = 'Email incorrect'
            if request.POST['special_admin_password'] != SpecialAdmin.password:
                error_set['password_incorrect'] = 'Password incorrect'
            if len(error_set) > 0:
                return render(request, 'special_admin/login.html', error_set)
            # Validating finished

            request.session['special_admin_logged'] = True
            return render(request, 'special_admin/home.html')

        # Logout request
        if 'log_out' in request.POST and request.POST['log_out'] == 'True':
            request.session['special_admin_logged'] = False
            return PerRedirect(reverse('special_admin:home'))

    # GET request
    elif request.method == 'GET':

        # special admin logged in
        if request.session.get(sk.special_admin_logged, False):
            return render(request, 'special_admin/home.html')
        # NOT logged in
        else:
            return render(request, 'special_admin/login.html')


def students(request):
    if request.method == 'POST':
        if 'delete' in request.POST:
            delete_student = get_object_or_404(Student, pk=request.POST['delete'])
            delete_student.delete()
            all_students = Student.objects.all()
            return render(request, 'special_admin/student_crud/students.html', {'all_students': all_students})

    elif request.method == 'GET':
        # special admin logged in
        if request.session.get(sk.special_admin_logged, False):
            all_students = Student.objects.all()
            return render(request, 'special_admin/student_crud/students.html', {'all_students': all_students})
        # NOT logged in
        else:
            return render(request, 'special_admin/login.html')


def new_student(request):
    all_courses = Course.objects.all()

    if request.method == 'POST':
        if 'courses' in request.POST:
            try:
                Student.objects.get(user_name=request.POST['student_user_name'])
                return render(request, 'special_admin/student_crud/new_student.html', {'all_courses': all_courses,
                                                                                       'message': 'User Name Already Exists'})
            except ObjectDoesNotExist:
                _new_student = Student(name=request.POST['student_name'], user_name=request.POST['student_user_name'])
                _new_student.save()

                courses_pks_str = request.POST['courses']
                courses_pks = courses_pks_str.split(',')
                if not courses_pks_str == '':
                    for course_pk in courses_pks:
                        course = Course.objects.get(pk=course_pk)
                        _new_student.course_set.add(course)
                        course.student_set.add(_new_student)

                return PerRedirect(reverse('special_admin:students'))

    elif request.method == 'GET':
        # special admin logged in
        if request.session.get(sk.special_admin_logged, False):
            return render(request, 'special_admin/student_crud/new_student.html', {'all_courses': all_courses})
        # NOT logged in
        else:
            return render(request, 'special_admin/login.html')


def old_student(request, pk):
    all_courses = Course.objects.all()
    selected_student = get_object_or_404(Student, pk=pk)

    if request.method == 'POST':
        # delete student
        if 'delete_student' in request.POST:
            selected_student.delete()
            return PerRedirect(reverse('special_admin:students'))

        # update student
        if 'courses' in request.POST:

            try:
                Student.objects.get(user_name=request.POST['student_user_name'])

                # user_name exists for some other fellow
                if request.POST['student_user_name'] != selected_student.user_name:
                    # getting new values
                    signed_courses = selected_student.course_set.all()
                    unsigned_courses = [course for course in all_courses if course not in signed_courses]
                    return render(request, 'special_admin/student_crud/old_student.html', {'student': selected_student,
                                                                                           'signed_courses': signed_courses,
                                                                                           'unsigned_courses': unsigned_courses,
                                                                                           'all_courses': all_courses,
                                                                                           'message': 'User Name Already Exists'})
                # user_name exists but for same fellow
                else:
                    # deleting previous course set
                    selected_student.course_set.clear()
                    # removing the current student from student sets of all courses
                    for course in all_courses:
                        course.student_set.remove(selected_student)

                    # update basic info
                    selected_student.name = request.POST['student_name']
                    selected_student.user_name = request.POST['student_user_name']

                    # update course set
                    courses_pks_str = request.POST['courses']
                    courses_pks = courses_pks_str.split(',')
                    selected_student.course_set.clear()

                    # only needed if course set is non empty
                    if not courses_pks_str == '':
                        for course_pk in courses_pks:
                            course = Course.objects.get(pk=course_pk)
                            selected_student.course_set.add(course)
                            course.student_set.add(selected_student)
                            course.save()

                    selected_student.save()

                    # getting new values
                    signed_courses = selected_student.course_set.all()
                    unsigned_courses = [course for course in all_courses if course not in signed_courses]
                    return render(request, 'special_admin/student_crud/old_student.html', {'student': selected_student,
                                                                                           'signed_courses': signed_courses,
                                                                                           'unsigned_courses': unsigned_courses,
                                                                                           'all_courses': all_courses,
                                                                                           'message': 'updated'})
            except ObjectDoesNotExist:
                # deleting previous course set
                selected_student.course_set.clear()
                # removing the current student from student sets of all courses
                for course in all_courses:
                    course.student_set.remove(selected_student)

                # update basic info
                selected_student.name = request.POST['student_name']
                selected_student.user_name = request.POST['student_user_name']

                # update course set
                courses_pks_str = request.POST['courses']
                courses_pks = courses_pks_str.split(',')
                selected_student.course_set.clear()

                # only needed if course set is non empty
                if not courses_pks_str == '':
                    for course_pk in courses_pks:
                        course = Course.objects.get(pk=course_pk)
                        selected_student.course_set.add(course)
                        course.student_set.add(selected_student)
                        course.save()

                selected_student.save()

                # getting new values
                signed_courses = selected_student.course_set.all()
                unsigned_courses = [course for course in all_courses if course not in signed_courses]
                return render(request, 'special_admin/student_crud/old_student.html', {'student': selected_student,
                                                                                       'signed_courses': signed_courses,
                                                                                       'unsigned_courses': unsigned_courses,
                                                                                       'all_courses': all_courses,
                                                                                       'message': 'updated'})

    if request.method == 'GET':
        # special admin logged in
        if request.session.get(sk.special_admin_logged, False):
            # getting course sets
            signed_courses = selected_student.course_set.all()
            unsigned_courses = [course for course in all_courses if course not in signed_courses]

django/special_admin/templates/special_admin/course_crud/courses.html
{% extends 'special_admin/base.html' %}
{% block body %}
    <div class="container-fluid">
        <h1 style="text-align: center;margin: 0;font-size: 50px">All these Courses !!</h1>
        <hr>
        <div class="row">
            <div class="col-xs-2">
                <a href="{% url 'special_admin:new_course' %}">
                    <button class="btn-success">Create</button>
                </a>
            </div>
            <div class="col-xs-8">
                <blockquote>{{ all_courses|length }} courses </blockquote>
                <table class="table table-hover table-striped" style="overflow: scroll">
                    <colgroup>
                        <col span="1" style="width: 10%;">
                        <col span="1" style="width: 50%;">
{#                        <col span="1" style="width: 10%;">#}
{#                        <col span="1" style="width: 15%;">#}
{#                        <col span="1" style="width: 15%;">#}
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Code</th>
                        <th>Name</th>
{#                        <th></th>#}
{#                        <th></th>#}
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for course in all_courses %}
                        <tr>
                            <td>
                                <a href="{% url 'special_admin:old_course' course.pk %}">
                                    {{ course.code }}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'special_admin:old_course' course.pk %}">
                                    {{ course.name }}
                                </a>
                            </td>
{#                            <td>#}
{#                                <a href="{% url 'special_admin:tasks' course.pk %}">#}
{#                                    <button class="btn-info">#}
{#                                        Tasks#}
{#                                    </button>#}
{#                                </a>#}
{#                            </td>#}
{#                            <td>#}
{#                                <a href="{% url 'special_admin:feedback_forms' course.pk %}">#}
{#                                    <button class="btn-default">#}
{#                                        Feedback#}
{#                                    </button>#}
{#                                </a>#}
{#                            </td>#}
                            <td>
                                <form action="{% url 'special_admin:courses' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="delete" value="{{ course.pk }}">
                                    <input type="submit" value="Delete" class="btn-danger">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

django/special_admin/templates/special_admin/course_crud/old_course.html
{% extends 'special_admin/base.html' %}
{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-xs-2"></div>
            <div class="col-xs-7">
                <h1 style="text-align: center;margin: 0;font-size: 50px">{{ course.name }}..</h1>
            </div>
            <div class="col-xs-1">
{#                <a href="{% url 'special_admin:tasks' course.pk %}">#}
{#                    <button class="btn-info" style="width: 100px;height: 50px;font-size: xx-large">#}
{#                        Tasks#}
{#                    </button>#}
{#                </a>#}
            </div>
            <div class="col-xs-2">
{#                <a href="{% url 'special_admin:feedback_forms' course.pk %}">#}
{#                    <button class="btn-default" style="width: 150px;height: 50px;font-size: xx-large">#}
{#                        Feedback#}
{#                    </button>#}
{#                </a>#}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-xs-2">
                <form method="post" action="{% url 'special_admin:old_course' course.pk %}" class="form-horizontal">
                    {% csrf_token %}
                    <input type="submit" name="delete_course" value="Delete" class="btn-danger">
                </form>
                <form method="post" action="{% url 'special_admin:old_course' course.pk %}" id="update_course_form">
                    {% csrf_token %}
                    <br>
                    <input style='width: 100%' type='text' id='course_code'  name='course_code' value='{{ course.code }}'
                           placeholder='code'><br><br>
                    <input style='width: 100%' type='text' name='course_name' value='{{ course.name }}'
                           placeholder='name'><br><br>
                    <input type="hidden" value="" id="students_input" name="students">
                    <input id="validate" type='button' name='update_course' value='Update' class='btn-info'>
                    <script type="text/javascript">
                        var signed_students = [];
                        var signed_class_name = 'signed';
                        var no_signed = {{ signed_students|length }};
                        var no_available = {{ unsigned_students|length }};

                        function update_totals() {
                            $('#no_students_available').text(no_available);
                            $('#no_students_signed').text(no_signed);
                        }

                        $(document).ready(function () {
                            $('#validate').click(function () {
                                if ($('#course_code').val() == "") {
                                    alert('Empty Course Code!');
                                    return;
                                }
                                if ($('#course_code').val().indexOf("`") != -1){
                                    alert('Course code cannot contain ` !');
                                    return;
                                }
                                signed_students = [];
                                $('#students_signed').find('.' + signed_class_name).each(function () {
                                    signed_students.push($(this).attr('id'));
                                });
                                $('#students_input').val(signed_students.join(","));
                                $('#update_course_form').submit();
                            });
                        });
                    </script>
                </form>
            </div>
            {#      Students enrollment script      #}
            <script type="text/javascript">
                $(document).ready(function () {
                    update_totals();

                    $('#students_signed').find('.course').click(function () {
                        $(this).fadeOut(0).removeClass(signed_class_name);
                        $('#students_available').find('#' + $(this).attr('id')).fadeIn(0);
                        no_available++;
                        no_signed--;
                        update_totals();
                    });
                    $('#students_available').find('.course').click(function () {
                        $(this).fadeOut(0);
                        $('#students_signed').find('#' + $(this).attr('id')).fadeIn(0).addClass(signed_class_name);
                        no_available--;
                        no_signed++;
                        update_totals();
                    });
                });
            </script>
            <div class='col-xs-5'>
                <blockquote><span id='no_students_signed'></span> students registered</blockquote>
                <table id='students_signed' class='table table-hover table-striped' style='overflow: scroll'>
                    <colgroup>
                        <col span="1" style="width: 50%;">
                        <col span="1" style="width: 50%;">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>User Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in all_students %}
                        <tr id='{{ student.pk }}'
                                {% if student not in signed_students %}
                            style="display: none"
                            class='course'
                                {% else %}
                            class='course signed'
                                {% endif %}>
                            <td>
                                <a href='{% url 'special_admin:old_student' student.pk %}'>
                                    {{ student.name }}
                                </a>
                            </td>
                            <td>
                                <a href='{% url 'special_admin:old_student' student.pk %}'>
                                    {{ student.user_name }}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class='col-xs-5'>
                <blockquote><span id='no_students_available'></span> students available</blockquote>
                <table id='students_available' class='table table-hover table-striped' style='overflow: scroll'>
                    <colgroup>
                        <col span="1" style="width: 50%;">
                        <col span="1" style="width: 50%;">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>User Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in all_students %}
                        <tr id='{{ student.pk }}' class='course'
                                {% if student not in unsigned_students %}
                            style="display: none"
                            class='course  signed'
                                {% else %}
                            class='course'
                                {% endif %}>
                            <td>
                                <a href='{% url 'special_admin:old_student' student.pk %}'>
                                    {{ student.name }}
                                </a>
                            </td>
                            <td>
                                <a href='{% url 'special_admin:old_student' student.pk %}'>
                                    {{ student.user_name }}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}